name: WakaTime Stats Update

on:
  schedule:
    - cron: "0 * * * *"  # This will update your stats every hour. You can adjust the timing.

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update Readme with Metrics
        uses: actions/checkout@v3

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
            